name: Docker Image CI

on:
  push:
    tags: 
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ephemerecreative/gitpod-workspace:${{github.ref_name}}
      - name: Push the docker image
        run: docker push ephemerecreative/gitpod-workspace:${{github.ref_name}}
